In [60]:
import numpy as np
arr = np.arange(16).reshape((2, 2, 4))


In [55]:
import numpy as np
arr = np.arange(24).reshape((2, 3, 4))

In [61]:
arr


array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [62]:
arr.transpose((1, 0,2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [63]:
arr.transpose((0, 2,1))

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

In [64]:
arr.transpose((2, 0,1))

array([[[ 0,  4],
        [ 8, 12]],

       [[ 1,  5],
        [ 9, 13]],

       [[ 2,  6],
        [10, 14]],

       [[ 3,  7],
        [11, 15]]])

In [59]:
arr.transpose((2, 1,0))

array([[[ 0, 12],
        [ 4, 16],
        [ 8, 20]],

       [[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]]])

In [7]:
# List comprehension-- 

[x**2 for x in range(0,10)]


[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [8]:
[i for i in range(1,101) if int(i**0.5)==i**0.5]

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

In [9]:
#Example 1 Flatten the matrix

def eg1_for(matrix):
    flat = []
    for row in matrix:
        for x in row:
            flat.append(x)
    return flat

def eg1_lc(matrix):
    return [x for row in matrix for x in row ]


In [10]:
print ("Original Matrix: " + str(arr))
print ("FOR-loop result: " + str(eg1_for(arr)))
print ("LC result      : " + str(eg1_lc(arr)))

Original Matrix: [[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]
FOR-loop result: [array([0, 1, 2, 3]), array([4, 5, 6, 7]), array([ 8,  9, 10, 11]), array([12, 13, 14, 15])]
LC result      : [array([0, 1, 2, 3]), array([4, 5, 6, 7]), array([ 8,  9, 10, 11]), array([12, 13, 14, 15])]


In [11]:
#Example 2: Removing vowels from a sentence

In [12]:
def eg2_for(sentence):
    vowels = 'aeiou'
    filtered_list = []
    for l in sentence:
        if l not in vowels:
            filtered_list.append(l)
    return ''.join(filtered_list)

def eg2_lc(sentence):
    vowels = 'aeiou'
    return ''.join([ l for l in sentence if l not in vowels])

In [13]:
sentence = 'My name is Sanjot Jain!'
print ("FOR-loop result: " + eg2_for(sentence))
print ("LC result      : " + eg2_lc(sentence))

FOR-loop result: My nm s Snjt Jn!
LC result      : My nm s Snjt Jn!


In [14]:
# Example 3: Dictionary Comprehension
def eg3_for(keys, values):
    dic = {}
    for i in range(len(keys)):
        dic[keys[i]] = values[i]
    return dic

def eg3_lc(keys, values):
    return { keys[i] : values[i] for i in range(len(keys)) }

In [15]:
country = ['India', 'Pakistan', 'Nepal', 'Bhutan', 'China', 'Bangladesh']
capital = ['New Delhi', 'Islamabad','Kathmandu', 'Thimphu', 'Beijing', 'Dhaka']
print ("FOR-loop result: " + str(eg3_for(country, capital)))
print ("LC result      : " + str(eg3_lc(country, capital)))

FOR-loop result: {'Bhutan': 'Thimphu', 'China': 'Beijing', 'India': 'New Delhi', 'Bangladesh': 'Dhaka', 'Nepal': 'Kathmandu', 'Pakistan': 'Islamabad'}
LC result      : {'Bhutan': 'Thimphu', 'China': 'Beijing', 'India': 'New Delhi', 'Bangladesh': 'Dhaka', 'Nepal': 'Kathmandu', 'Pakistan': 'Islamabad'}


In [16]:
#Method 1: For-Loop
def square_for(arr):
    result = []
    for i in arr:
        result.append(i**2)
    return result
%timeit square_for(range(1,11))

4.92 µs ± 108 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [17]:
#Method 2: Map Function
def square_map(arr):
    return map(lambda x: x**2, arr)
%timeit square_map(range(1,11))

915 ns ± 139 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [18]:
#Method 3: List comprehension:
def square_lc(arr):
    return [i**2 for i in arr]
%timeit square_lc(range(1,11))

4.42 µs ± 61.5 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [19]:
#Method 1: For-Loop
def square_even_for(arr):
    result = []
    for i in arr:
        if i%2 == 0:
            result.append(i**2)
    return result
%timeit square_even_for(range(1,11))

3.77 µs ± 60.4 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [20]:
print(square_for(range(1,11)))
print(square_lc(range(1,11)))
a= square_map(range(1,11))
for d in a:
    print(d)


[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]
[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]
1
4
9
16
25
36
49
64
81
100


In [23]:
#Method 2: Map Function
def square_even_map(arr):
    return filter(lambda x: x is not None,map(lambda x: x**2 if x%2==0 else None, arr))
%timeit square_even_map(range(1,11))

997 ns ± 45.9 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [ ]:
#Method 3: List comprehension:
def square_even_lc(arr):
    return [i**2 for i in arr if i%2==0]
%timeit square_even_lc(range(1,11))

In [24]:

a= square_even_map(range(1,11))
for d in a:
    print(d)
    

4
16
36
64
100


In [27]:
cols = ['a','b','c','d','a_transform','b_transform','c_transform','d_power2','d_power3','d_power4','d_power5','temp1','temp2']
cols

['a',
 'b',
 'c',
 'd',
 'a_transform',
 'b_transform',
 'c_transform',
 'd_power2',
 'd_power3',
 'd_power4',
 'd_power5',
 'temp1',
 'temp2']

In [ ]:
col_set1 = [x for x in cols if x.endswith('transform')]
col_set2 = [x for x in cols if 'power' in x]
col_set3 = [x for x in cols if (x.endswith('transform')) | ('power' in x)]
col_set4 = [x for x in cols if x not in ['temp1','temp2']]
print ('Set1: ', col_set1)
print ('Set2: ', col_set2)
print ('Set3: ', col_set3)
print ('Set4: ', col_set4)

In [ ]:
def cube(y):
    return y*y*y;
 
g = lambda x: x*x*x
print(g(7))
 
print(cube(5))

In [29]:
li = [5, 7, 22, 97, 54, 62, 77, 23, 73, 61]
final_list = list(filter(lambda x: (x%2 != 0) , li))
print(final_list)

[5, 7, 97, 77, 23, 73, 61]


In [30]:
li = [5, 7, 22, 97, 54, 62, 77, 23, 73, 61]
final_list = list(map(lambda x: x*2 , li))
print(final_list)

[10, 14, 44, 194, 108, 124, 154, 46, 146, 122]


In [39]:
from functools import reduce
li = [5, 8, 10, 20, 50, 100]
g = lambda x,y: x+y
for i in range(len(li)):
    print(g(li[i],li[i+1]))
print(g(5,7))
sum = reduce((lambda x, y: x + y), li)
sum1 = reduce((lambda x, y: x + y), li)
print (sum)

13
18
30
70
150


IndexError: list index out of range

In [40]:
# Function to rearrange positive and negative elements
def Rearrange(arr):
 
    # First lambda expression returns list of negative numbers
    # in arr.
    # Second lambda expression returns list of positive numbers
    # in arr.
    return [x for x in arr if x < 0] + [x for x in arr if x >= 0]
 
# Driver function
if __name__ == "__main__":
    arr = [12, 11, -13, -5, 6, -7, 5, -3, -6]
    print( Rearrange(arr))


[-13, -5, -7, -3, -6, 12, 11, 6, 5]


In [ ]:
# Python program to count
# occurrences of an 
# element in an unsorted 
# array
def frequency(a, x):
    count = 0
     
    for i in a:
        if i == x: count += 1
    return count
 
# Driver program
a = [0, 5, 5, 5, 4]
x = 5
print(frequency(a, x))

In [25]:
# Python program to
# answer queries for
# frequencies
# in O(1) time.
 
hm = {}
 
def countFreq(a):
    global hm
     
    # Insert elements and their 
    # frequencies in hash map.
     
    for i in a:
        if i in hm: hm[i] += 1
        else: hm[i] = 1
 
# Return frequency 
# of x (Assumes that 
# countFreq() is 
# called before)
def query(x):
    if x in hm:
        return hm[x]
    return 0
 
# Driver program
a = [1, 3, 2, 4, 2, 1]
countFreq(a)
print(query(2))
print(query(3))
print(query(5))

2
1
0


In [28]:
import os
for root, dirs, files in os.walk("."):
    print(root)
    print(dirs)
    print(files)
    for file in files:
        if file.endswith(".ipynb"):
             print(os.path.join(root, file))
                

.
['.ipynb_checkpoints']
['Revision.ipynb']
./Revision.ipynb
./.ipynb_checkpoints
[]
['Revision-checkpoint.ipynb']
./.ipynb_checkpoints/Revision-checkpoint.ipynb


In [48]:


#Find a file in python
import os

def find(name, path):
    for root, dirs, files in os.walk(path):
        if name in files:
            return os.path.join(root, name)

In [51]:
print(find('Revision.ipynb', '.'))

./Revision.ipynb


In [42]:
def find_all(name, path):
    result = []
    for root, dirs, files in os.walk(path):
        if name in files:
            result.append(os.path.join(root, name))
    return result

In [43]:
import os, fnmatch
def find(pattern, path):
    result = []
    for root, dirs, files in os.walk(path):
        for name in files:
            if fnmatch.fnmatch(name, pattern):
                result.append(os.path.join(root, name))
    return result

find('*.ipynb', '.')

['./Revision.ipynb', './.ipynb_checkpoints/Revision-checkpoint.ipynb']

In [44]:
reduce(lambda x,y: x+y, [47,11,42,13])

113

In [45]:
squares = map(lambda x: x * x, [0, 1, 2, 3, 4])

print (squares)

In [ ]:
sum = reduce(lambda a, x: a + x, [0, 1, 2, 3, 4])

print (sum)

In [52]:
sentences = ['Mary read a story to Sam and Isla.',
             'Isla cuddled Sam.',
             'Sam chortled.']

sam_count = reduce(lambda a, x: a + x.count('Sam'),
                   sentences,
                   0)
print(sam_count)

3


In [47]:
people = [{'name': 'Mary', 'height': 160},
          {'name': 'Isla', 'height': 80},
          {'name': 'Sam'}]

height_total = 0
height_count = 0
for person in people:
    if 'height' in person:
        height_total += person['height']
        height_count += 1

if height_count > 0:
    average_height = height_total / height_count

    print (average_height)
    

120.0


In [ ]:
people = [{'name': 'Mary', 'height': 160},
          {'name': 'Isla', 'height': 80},
          {'name': 'Sam'}]

heights = map(lambda x: x['height'],
              filter(lambda x: 'height' in x, people))
len1 = len(list((heights)))
print(len1)
if len1 > 0:
    from operator import add
    average_height = reduce(add, heights) / len1