### Numpy basic---Numerical Python

Fundamental package required for high performance scientific computing and data analysis

ndarray-- Fast and space -efficient multidimensional array 
providing vectorized operation and sophasticated broadcasting capacity 

Standered mathematical operation across the arry w/o loops 

Tools for reading writing data to disk and in memory files

Tools to integrate code written in c, c++ and fortorn


Fast vectorized array operations for data munging and cleaning, subsetting and filtering, transformation, and any other kinds of computations

Common array algorithms like sorting, unique, and set operations

Efficient descriptive statistics and aggregating/summarizing data

Data alignment and relational data manipulations for merging and joining together heterogeneous data sets

Expressing conditional logic as array expressions instead of loops with if-elif- else branches

Group-wise data manipulations (aggregation, transformation, function applica- tion).











In [2]:
import numpy as np
data1 = [6, 7.5, 8, 0, 1]
arra1 = np.array(data1)

In [3]:
arra1
type(arra1)


numpy.ndarray

In [4]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]

In [5]:
arr2 = np.array(data2)

In [6]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [7]:
arr2.ndim

2

In [8]:
arr2.shape

(2, 4)

In [9]:
arr2.dtype

dtype('int64')

In [10]:
arra1.dtype

dtype('float64')

In [11]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [12]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [13]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [14]:
arra3 = np.empty((2,3,2))


In [15]:
arra3

array([[[0.00000000e+00, 0.00000000e+00],
        [0.00000000e+00, 0.00000000e+00],
        [0.00000000e+00, 0.00000000e+00]],

       [[0.00000000e+00, 0.00000000e+00],
        [0.00000000e+00, 0.00000000e+00],
        [0.00000000e+00, 5.64435529e-62]]])

In [16]:
arra3.ndim

3

In [17]:
arra3.shape

(2, 3, 2)

In [18]:
np.arange(14)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

array --Convert input data (list, tuple, array, or other sequence type) to an ndarray either by inferring a dtype or explicitly specifying a dtype. Copies the input data by default.

asarray --Convert input to ndarray, but do not copy if the input is already an ndarray

arange - Like the built-in range but returns an ndarray instead of a list.

ones, ones_like - Produce an array of all 1’s with the given shape and dtype. ones_like takes another array and produces a ones array of the same shape and dtype.

zeros and zeros_like --Like ones and ones_like but producing arrays of 0’s instead

empty, empty_like-- Create new arrays by allocating new memory, but do not populate with any values like ones and zeros

eye, identity -- 
Create a square N x N identity matrix (1’s on the diagonal and 0’s elsewhere)


The data type or dtype is a special object containing the information the ndarray needs to interpret a chunk of memory as a particular type of data:

dtypes - generally map directly on to underlying machine representation which makes it easy to read and write binary strems of data disk and also esaily connect to program written in c, c++ or Fortorn

In [19]:
import numpy as np
np.__version__

'1.15.3'

In [20]:
np?

In [21]:
arr1 = np.array([1, 2, 3], dtype=np.float64)

In [22]:
arr2 = np.array([1, 2, 3], dtype=np.int32)

In [23]:
arr1.dtype

dtype('float64')

In [24]:
arr2.dtype

dtype('int32')

In [25]:
## casting of array 

arr = np.array([1, 2, 3, 4, 5])
arr.dtype


dtype('int64')

In [26]:
float_arr = arr.astype(np.float64)

In [27]:
float_arr.dtype

dtype('float64')

In [28]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [29]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10], dtype=int32)

In [30]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)

In [31]:
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

In [32]:
int_array = np.arange(10)

In [33]:
int_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
 calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)

In [35]:
calibers

array([0.22 , 0.27 , 0.357, 0.38 , 0.44 , 0.5  ])

In [36]:
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [39]:
# Python Program to create a data type object  
# containing a 32 bit big-endian integer 
import numpy as np 
  
# i4 represents integer of size 4 byte 
# > represents big-endian byte ordering and < represents little-endian encoding. 
# dt is a dtype object 
dt = np.dtype('>i4') 
  
print("Byte order is:",dt.byteorder) 
  
print("Size is:",dt.itemsize) 
  
print("Data type is:",dt.name) 

Byte order is: >
Size is: 4
Data type is: int32


In [37]:
 empty_uint32 = np.empty(8, dtype='u4')

In [40]:
empty_uint32

array([         0,          0,          0,          0,   56492062,
                1,  276084697, 2147483648], dtype=uint32)

In [41]:
np.random.seed(0) # seed for reproducibility
x1 = np.random.randint(10, size=6) # One-dimensional array
x2 = np.random.randint(10, size=(3, 4)) # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5)) # Three-dimensional array


In [42]:
print("x3 ndim: ", x3.ndim) 
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)


x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60


In [43]:
x3

array([[[8, 1, 5, 9, 8],
        [9, 4, 3, 0, 3],
        [5, 0, 2, 3, 8],
        [1, 3, 3, 3, 7]],

       [[0, 1, 9, 9, 0],
        [4, 7, 3, 2, 7],
        [2, 0, 0, 4, 5],
        [5, 6, 8, 4, 1]],

       [[4, 9, 8, 1, 1],
        [7, 9, 9, 3, 6],
        [7, 2, 0, 3, 5],
        [9, 4, 4, 6, 4]]])

Calling astype always creates a new array (a copy of the data), even if
the new dtype is the same as the old dtype.

###  Operations between Arrays and Scalars

Arrays are important because they enable you to express batch operations on data without writing any for loops. This is usually called vectorization. Any arithmetic op- erations between equal-size arrays applies the operation elementwise


Operations between differently sized arrays is called broadcasting 

In [44]:
arr =np.array([[1., 2., 3.], [4., 5., 6.]])

In [45]:
arr




array([[1., 2., 3.],
       [4., 5., 6.]])

In [46]:
arr*arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [47]:
1/arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [48]:
arr = np.arange(10)

In [49]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
# arrary slicing - x[start:stop:step]
arr[5]

5

In [51]:
arr[2:5]

array([2, 3, 4])

In [52]:
arr[2:5] = 12

In [53]:
arr

array([ 0,  1, 12, 12, 12,  5,  6,  7,  8,  9])

In [54]:
arr[2:5]

array([12, 12, 12])

Assiagn a scalar value to a slice, as in arr[2:5] = 12,The value is propagated (or broadcasted ) to the entire selection

An important first dis- tinction from lists is that array slices are views on the original array. This means that the data is not copied, and any modifications to the view will be reflected in the source array:


If you want a copy of a slice of an ndarray instead of a view, you will need to explicitly copy the array; for example arr[5:8].copy().

In [55]:
arr_slice = arr[5:8]

In [56]:
arr_slice

array([5, 6, 7])

In [57]:
arr_slice[1] = 12345

In [58]:
arr_slice

array([    5, 12345,     7])

In [59]:
arr

array([    0,     1,    12,    12,    12,     5, 12345,     7,     8,
           9])

In [60]:
arr_slice[:] = 70

In [61]:
arr_slice

array([70, 70, 70])

In [62]:
arr

array([ 0,  1, 12, 12, 12, 70, 70, 70,  8,  9])

In [63]:
 arr[::-1] # all elements, reversed

array([ 9,  8, 70, 70, 70, 12, 12, 12,  1,  0])

In [64]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d.ndim
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [61]:
arr2d[2]

array([7, 8, 9])

In [65]:
arr2d[0][2]

3

In [66]:
arr2d[2][2]

9

In [67]:
arr2d[0, 2]

3

In multidimensional arrays, if you omit later indices, the returned object will be a lower- dimensional ndarray consisting of all the data along the higher dimensions


In [68]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [69]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [70]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [71]:
arr3d[0].ndim

2

In [72]:
arr3d[0].shape

(2, 3)

In [73]:
arr3d.ndim

3

In [74]:
old_values = arr3d[0].copy()

In [75]:
old_values

array([[1, 2, 3],
       [4, 5, 6]])

In [76]:
arr3d[0] =34

In [77]:
arr3d

array([[[34, 34, 34],
        [34, 34, 34]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [78]:
arr3d[0]

array([[34, 34, 34],
       [34, 34, 34]])

In [76]:
arr3d[0] = old_values

In [77]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [79]:
arr3d

array([[[34, 34, 34],
        [34, 34, 34]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [80]:
arr3d[1, 0]  
#Givesyouallofthevalueswhoseindicesstartwith(1, 0),form-
# ing a 1-dimensional array:'''

array([7, 8, 9])

In [81]:
arr[1:6]

array([ 1, 12, 12, 12, 70])

In [82]:
arr

array([ 0,  1, 12, 12, 12, 70, 70, 70,  8,  9])

In [83]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [84]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [85]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [86]:
arr2d[1, :2]

array([4, 5])

In [87]:
arr2d[2, :1]

array([7])

In [88]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [89]:
 x2[:2, :3] # two rows, three columns

array([[3, 5, 2],
       [7, 6, 8]])

Colon by itself means to take the entire axis, so you can slice only higher dimensional axes by doing:

In [90]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

In [93]:
arr2d[:2, 1:] = 0

In [94]:
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

In [95]:
names = np.array(['Bob', 'Bob', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [96]:
names

array(['Bob', 'Bob', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [97]:
data = np.random.randn(7, 4)

In [98]:
data

array([[ 1.25441407,  1.41910204, -0.74385608, -2.5174371 ],
       [-1.50709602,  1.14907613, -1.19357825,  1.14104245],
       [ 1.50944508,  1.06777513, -0.68658948,  0.01487332],
       [-0.3756659 , -0.03822364,  0.36797447, -0.0447237 ],
       [-0.30237513, -2.2244036 ,  0.72400636,  0.35900276],
       [ 1.07612104,  0.19214083,  0.85292596,  0.01835718],
       [ 0.42830357,  0.99627783, -0.49114966,  0.71267817]])

In [99]:
names == 'Bob'

array([ True,  True, False,  True, False, False, False])

In [100]:
 # Suppose each name corresponds to a row in the data array
data[names == 'Bob']
# The boolean array must be of the same length as the axis it’s indexing.

array([[ 1.25441407,  1.41910204, -0.74385608, -2.5174371 ],
       [-1.50709602,  1.14907613, -1.19357825,  1.14104245],
       [-0.3756659 , -0.03822364,  0.36797447, -0.0447237 ]])

In [101]:
data[names == 'Bob'].ndim

2

In [102]:
data[names == 'Bob'].shape

(3, 4)

In [104]:
 data[names == 'Bob', 2:]

array([[-0.74385608, -2.5174371 ],
       [-1.19357825,  1.14104245],
       [ 0.36797447, -0.0447237 ]])

In [105]:
data[names == 'Bob', 3]

array([-2.5174371 ,  1.14104245, -0.0447237 ])

In [106]:
data[~(names == 'Bob')]

array([[ 1.50944508,  1.06777513, -0.68658948,  0.01487332],
       [-0.30237513, -2.2244036 ,  0.72400636,  0.35900276],
       [ 1.07612104,  0.19214083,  0.85292596,  0.01835718],
       [ 0.42830357,  0.99627783, -0.49114966,  0.71267817]])

In [107]:
~(names == 'Bob')

array([False, False,  True, False,  True,  True,  True])

In [108]:
mask = (names == 'Bob') | (names == 'Will')


In [109]:
mask

array([ True,  True,  True,  True,  True, False, False])

In [110]:
data[mask]

array([[ 1.25441407,  1.41910204, -0.74385608, -2.5174371 ],
       [-1.50709602,  1.14907613, -1.19357825,  1.14104245],
       [ 1.50944508,  1.06777513, -0.68658948,  0.01487332],
       [-0.3756659 , -0.03822364,  0.36797447, -0.0447237 ],
       [-0.30237513, -2.2244036 ,  0.72400636,  0.35900276]])

Selecting data from an array by boolean indexing always creates a copy of the data, even if the returned array is unchanged.

The Python keywords and and or do not work with boolean arrays.

In [111]:
# To set all of the negative values in data to 0
data[(data < 0)|(data >1) ] = 4



In [112]:
data

array([[4.        , 4.        , 4.        , 4.        ],
       [4.        , 4.        , 4.        , 4.        ],
       [4.        , 4.        , 4.        , 0.01487332],
       [4.        , 4.        , 0.36797447, 4.        ],
       [4.        , 4.        , 0.72400636, 0.35900276],
       [4.        , 0.19214083, 0.85292596, 0.01835718],
       [0.42830357, 0.99627783, 4.        , 0.71267817]])

In [113]:
# Setting whole rows or columns using a 1D boolean array
data[names != 'Joe'] = 7

In [114]:
data

array([[7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [4.        , 0.19214083, 0.85292596, 0.01835718],
       [0.42830357, 0.99627783, 4.        , 0.71267817]])

### Fancy Indexing

Fancy indexing is a term adopted by NumPy to describe indexing using integer arrays.

In [5]:
import numpy as np 
arr = np.empty((8, 4))

In [6]:
arr


array([[2.18248499e-314, 2.18248477e-314, 2.18347663e-314,
        2.18235854e-314],
       [2.22482276e-314, 2.22543384e-314, 2.18248444e-314,
        2.19256933e-314],
       [2.21232165e-314, 2.18253481e-314, 2.18371914e-314,
        2.19009091e-314],
       [2.18298936e-314, 2.18239268e-314, 2.18856128e-314,
        2.18298872e-314],
       [2.18459221e-314, 2.21134823e-314, 2.22543387e-314,
        2.18236068e-314],
       [2.18497366e-314, 2.18236942e-314, 2.18253583e-314,
        2.18299675e-314],
       [2.18236488e-314, 2.18267350e-314, 2.18243939e-314,
        2.21212835e-314],
       [2.18237028e-314, 2.18344350e-314, 2.18248510e-314,
        2.18499892e-314]])

In [7]:
for i in range(8):
    arr[i] = i

In [8]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [9]:
arr[[4, 3, 0, 6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [10]:
# Using negative indices select rows from the end
arr[[-3, -5, -7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [11]:
arr[5::-1] # reversed every other from index 5


array([[5., 5., 5., 5.],
       [4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [2., 2., 2., 2.],
       [1., 1., 1., 1.],
       [0., 0., 0., 0.]])

In [122]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [14]:
arr = np.arange(32).reshape((8, 4))


In [15]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [16]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

array([ 4, 23, 29, 10])

In [17]:
arr[[1, 5, 7, 2]][:, [0, 3, 1 ]]

array([[ 4,  7,  5],
       [20, 23, 21],
       [28, 31, 29],
       [ 8, 11,  9]])

Another way is to use the np.ix_ function, which converts two 1D integer arrays to an indexer that selects the square region:

fancy indexing, unlike slicing, always copies the data into a new array.

In [128]:
arr[np.ix_([1, 5, 7, 2], [0, 3, 1, 2])]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [129]:
arr = np.arange(15).reshape((3, 5))

In [130]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [131]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [132]:
arr = np.random.randn(6, 3)

In [135]:
arr

array([[ 1.11334035, -2.15367459, -0.41611148],
       [-1.07089699,  0.22113881, -1.12305712],
       [-1.05075796,  1.01207905,  1.54371643],
       [-0.40211489,  0.8647491 , -0.22686923],
       [ 0.81116027,  0.28779461, -0.53846816],
       [ 1.9084621 , -0.475776  ,  1.44073112]])

In [134]:
np.dot(arr.T, arr)

array([[ 7.95234434, -4.72032122,  1.52135671],
       [-4.72032122,  6.76850016,  1.17356179],
       [ 1.52135671,  1.17356179,  6.23459023]])

In [18]:
arr = np.arange(16).reshape((2, 2, 4))

In [19]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [20]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [22]:
arr.transpose((2, 0, 1))

array([[[ 0,  4],
        [ 8, 12]],

       [[ 1,  5],
        [ 9, 13]],

       [[ 2,  6],
        [10, 14]],

       [[ 3,  7],
        [11, 15]]])

Simple transposing with .T is just a special case of swapping axes. ndarray has the method swapaxes which takes a pair of axis numbers

In [141]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [142]:
arr.swapaxes(0, 2).swapaxes(2,1)

array([[[ 0,  4],
        [ 8, 12]],

       [[ 1,  5],
        [ 9, 13]],

       [[ 2,  6],
        [10, 14]],

       [[ 3,  7],
        [11, 15]]])

### Universal Functions: Fast Element-wise Array Function


A universal function, or ufunc, is a function that performs elementwise operations on data in ndarrays. You can think of them as fast vectorized wrappers for simple functions that take one or more scalar values and produce one or more scalar results.

In [143]:
arr = np.arange(10)

In [144]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [145]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [146]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [147]:
x = np.random.randn(8)

In [148]:
x

array([-1.14907568,  0.80571455,  1.75610703,  0.97297991, -1.55111911,
        0.19114348,  1.60477607, -1.42002593])

In [149]:
y = np.random.randn(8)

In [150]:
y

array([-2.44378268, -2.05633855, -0.99225755,  1.01128532,  1.40044008,
       -0.65499168, -0.25579069, -0.71438561])

In [151]:
np.maximum(x, y) # element-wise maximum

array([-1.14907568,  0.80571455,  1.75610703,  1.01128532,  1.40044008,
        0.19114348,  1.60477607, -0.71438561])

While not common, a ufunc can return multiple arrays. modf is one example, a vector- ized version of the built-in Python divmod: it returns the fractional and integral parts of a floating point array:

In [152]:
arr = np.random.randn(7) * 5

In [153]:
arr

array([-2.50419383,  0.27822671, -2.44480892, -1.89961223,  1.29867327,
       -8.40674321, -4.58397403])

In [154]:
np.modf(arr)

(array([-0.50419383,  0.27822671, -0.44480892, -0.89961223,  0.29867327,
        -0.40674321, -0.58397403]), array([-2.,  0., -2., -1.,  1., -8., -4.]))

abs, fabs --Compute the absolute value element-wise for integer, floating point, or complex values. Use fabs as a faster alternative for non-complex-valued data

sqrt -- Compute the square root of each element. Equivalent to arr ** 0.5

square -- Compute the square of each element. Equivalent to arr ** 2

exp -- Compute the exponent ex of each element

log, log10, log2, log1p -- Natural logarithm (base e), log base 10, log base 2, and log(1 + x), respectively

sign -- Compute the sign of each element: 1 (positive), 0 (zero), or -1 (negative)

ceil -- Compute the ceiling of each element, i.e. the smallest integer greater than or equal to each element

floor -- Compute the floor of each element, i.e. the largest integer less than or equal to each element

rint -- Round elements to the nearest integer, preserving the dtype

modf -- Return fractional and integral parts of array as separate array

isnan -- Return boolean array indicating whether each value is NaN (Not a Number)

isfinite, isinf -- Return boolean array indicating whether each element is finite (non-inf, non-NaN) or infinite, respectively


cos, cosh, sin, sinh,tan, tanh -- Regular and hyperbolic trigonometric functions

arccos, arccosh, arcsin, arcsinh, arctan, arctanh -- Inverse trigonometric functions

logical_not -- Compute truth value of not x element-wise. Equivalent to -arr.

Binary universal functions

add -- Add corresponding elements in arrays

subtract --Subtract elements in second array from first array

multiply -- Multiply array elements

divide, floor_divide -- Divide or floor divide (truncating the remainder)

power -- Raise elements in first array to powers indicated in second array

maximum, fmax -- Element-wise maximum. fmax ignores NaN

minimum, fmin -- Element-wise minimum. fmin ignores NaN

mod -- Element-wise modulus (remainder of division)

copysign -- Copy sign of values in second argument to values in first argument

greater, greater_equal, less, less_equal, equal, not_equal -- Perform element-wise comparison, yielding boolean array. Equivalent to infix operators  >, >=, <, <=, ==, !=

logical_and,logical_or, logical_xor  -- Compute element-wise truth value of logical operation. Equivalent to infix operators & |, ^


In [155]:
points = np.arange(-5, 5, 0.01)  # 1000 equally spaced points

In [156]:
points

array([-5.0000000e+00, -4.9900000e+00, -4.9800000e+00, -4.9700000e+00,
       -4.9600000e+00, -4.9500000e+00, -4.9400000e+00, -4.9300000e+00,
       -4.9200000e+00, -4.9100000e+00, -4.9000000e+00, -4.8900000e+00,
       -4.8800000e+00, -4.8700000e+00, -4.8600000e+00, -4.8500000e+00,
       -4.8400000e+00, -4.8300000e+00, -4.8200000e+00, -4.8100000e+00,
       -4.8000000e+00, -4.7900000e+00, -4.7800000e+00, -4.7700000e+00,
       -4.7600000e+00, -4.7500000e+00, -4.7400000e+00, -4.7300000e+00,
       -4.7200000e+00, -4.7100000e+00, -4.7000000e+00, -4.6900000e+00,
       -4.6800000e+00, -4.6700000e+00, -4.6600000e+00, -4.6500000e+00,
       -4.6400000e+00, -4.6300000e+00, -4.6200000e+00, -4.6100000e+00,
       -4.6000000e+00, -4.5900000e+00, -4.5800000e+00, -4.5700000e+00,
       -4.5600000e+00, -4.5500000e+00, -4.5400000e+00, -4.5300000e+00,
       -4.5200000e+00, -4.5100000e+00, -4.5000000e+00, -4.4900000e+00,
       -4.4800000e+00, -4.4700000e+00, -4.4600000e+00, -4.4500000e+00,
      

In [157]:
xs, ys = np.meshgrid(points, points)

In [158]:
ys

array([[-5.  , -5.  , -5.  , ..., -5.  , -5.  , -5.  ],
       [-4.99, -4.99, -4.99, ..., -4.99, -4.99, -4.99],
       [-4.98, -4.98, -4.98, ..., -4.98, -4.98, -4.98],
       ...,
       [ 4.97,  4.97,  4.97, ...,  4.97,  4.97,  4.97],
       [ 4.98,  4.98,  4.98, ...,  4.98,  4.98,  4.98],
       [ 4.99,  4.99,  4.99, ...,  4.99,  4.99,  4.99]])

In [159]:
 xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])

In [160]:
 yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])

In [161]:
cond = np.array([True, False, True, True, False])

In [162]:
xarr

array([1.1, 1.2, 1.3, 1.4, 1.5])

In [163]:
yarr

array([2.1, 2.2, 2.3, 2.4, 2.5])

In [164]:
cond

array([ True, False,  True,  True, False])

In [165]:
result = [(x if c else y)for x, y, c in zip(xarr, yarr, cond)]

In [166]:
result

[1.1, 2.2, 1.3, 1.4, 2.5]

In [167]:
result = np.where(cond, xarr, yarr)

In [168]:
result

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [169]:
arr = np.random.randn(4, 4)

In [170]:
arr

array([[-0.1192241 , -0.44627728, -2.14335544,  0.01003777],
       [-0.55822259,  0.48090565, -0.57414201, -0.2524676 ],
       [ 1.03984679, -0.02347953,  0.08942229, -0.59432737],
       [-0.10569679,  0.74279571, -0.75498153, -0.13828271]])

In [171]:
np.where(arr > 0, 2, -2)

array([[-2, -2, -2,  2],
       [-2,  2, -2, -2],
       [ 2, -2,  2, -2],
       [-2,  2, -2, -2]])

In [172]:
np.where(arr > 0, 2, arr) # set only positive values to 2

array([[-0.1192241 , -0.44627728, -2.14335544,  2.        ],
       [-0.55822259,  2.        , -0.57414201, -0.2524676 ],
       [ 2.        , -0.02347953,  2.        , -0.59432737],
       [-0.10569679,  2.        , -0.75498153, -0.13828271]])

### Mathematical and Statistical Methods

In [173]:
arr = np.random.randn(5, 4) # normally-distributed data

In [174]:
arr

array([[-2.12492027e+00, -1.03001883e+00, -5.17451865e-01,
        -1.41800012e-01],
       [-1.27648021e+00,  1.48151328e+00,  1.65927664e+00,
         1.39611962e-04],
       [ 1.50583836e+00,  1.04520923e-01, -2.36043151e-01,
         8.19435034e-01],
       [ 4.02856439e-01, -1.43824188e+00,  2.71248834e-01,
        -6.90603124e-01],
       [-6.81532976e-01, -1.51223065e+00,  2.19689103e+00,
         1.04117502e+00]])

In [175]:
arr.mean()

-0.008321390362050107

In [176]:
np.mean(arr)

-0.008321390362050107

In [177]:
arr.sum()

-0.16642780724100215

In [178]:
 arr.mean(axis=1)

array([-0.95354774,  0.46611233,  0.54843779, -0.36368493,  0.26107561])

In [179]:
arr.sum(0)

array([-2.17423866, -2.39445716,  3.37392149,  1.02834653])

In [180]:
 arr = np.array([[0, 1, 2], [3,
4, 5], [6, 7, 8]])

In [181]:
arr



array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [182]:
 arr.cumsum(0)

array([[ 0,  1,  2],
       [ 3,  5,  7],
       [ 9, 12, 15]])

In [183]:
arr.cumprod(1)

array([[  0,   0,   0],
       [  3,  12,  60],
       [  6,  42, 336]])

In [184]:
arr = np.random.randn(100)

In [185]:
(arr > 0).sum() # Number of positive values

48

In [186]:
bools = np.array([False, False, True, False])

In [187]:
bools.any()

True

In [188]:
bools.all()

False

In [189]:
arr = np.random.randn(8)

In [190]:
arr


array([-0.41522808, -0.63908615,  2.49776759, -3.00512816, -0.87399723,
       -2.65018924,  1.12400545, -0.21363701])

In [191]:
arr.sort()

In [192]:
arr

array([-3.00512816, -2.65018924, -0.87399723, -0.63908615, -0.41522808,
       -0.21363701,  1.12400545,  2.49776759])

In [193]:
arr = np.random.randn(5, 3)

In [194]:
arr

array([[ 1.13183157,  0.03723304,  1.30275033],
       [ 0.24990045, -0.64586771,  0.47119601],
       [-0.39810329, -0.95921519,  0.54087305],
       [-0.07824546,  1.83379274,  1.0246933 ],
       [-0.08166743, -2.62754439, -0.35645775]])

In [195]:
arr.sort(0)

In [196]:
arr

array([[-0.39810329, -2.62754439, -0.35645775],
       [-0.08166743, -0.95921519,  0.47119601],
       [-0.07824546, -0.64586771,  0.54087305],
       [ 0.24990045,  0.03723304,  1.0246933 ],
       [ 1.13183157,  1.83379274,  1.30275033]])

The top level method np.sort returns a sorted copy of an array instead of modifying the array in place

In [197]:
large_arr = np.random.randn(1000)

In [198]:
large_arr.sort()

In [199]:
large_arr[int(0.05 * len(large_arr))]  # 5% quantile

-1.6245819489248885

In [200]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [201]:
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [202]:
ints = np.array([3, 3, 3, 2, 2, 1, 1, 4, 4])

In [203]:
np.unique(ints)

array([1, 2, 3, 4])

In [204]:
## Contrast np.unique with the pure Python alternative:
sorted(set(names))

['Bob', 'Joe', 'Will']

In [205]:
values = np.array([6, 0, 0, 3, 2, 5, 6])

In [206]:
np.in1d(values, [2, 3, 6])

array([ True, False, False,  True,  True, False,  True])

In [23]:
help(np.in1d)

Help on function in1d in module numpy.lib.arraysetops:

in1d(ar1, ar2, assume_unique=False, invert=False)
    Test whether each element of a 1-D array is also present in a second array.
    
    Returns a boolean array the same length as `ar1` that is True
    where an element of `ar1` is in `ar2` and False otherwise.
    
    We recommend using :func:`isin` instead of `in1d` for new code.
    
    Parameters
    ----------
    ar1 : (M,) array_like
        Input array.
    ar2 : array_like
        The values against which to test each value of `ar1`.
    assume_unique : bool, optional
        If True, the input arrays are both assumed to be unique, which
        can speed up the calculation.  Default is False.
    invert : bool, optional
        If True, the values in the returned array are inverted (that is,
        False where an element of `ar1` is in `ar2` and True otherwise).
        Default is False. ``np.in1d(a, b, invert=True)`` is equivalent
        to (but is faster than) ``

In [207]:
arr = np.arange(10)

In [208]:
#  Arrays are saved by default in an uncompressed raw binary format with file extension .npy.
np.save('some_array', arr)

In [209]:
#If the file path does not already end in .npy, the extension will be appended. 
#The array on disk can then be loaded using np.load:
np.load('some_array.npy')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [210]:
# You save multiple arrays in a zip archive using np.savez and passing the arrays as key- word arguments:
np.savez('array_archive.npz', a=arr, b=arr)

In [25]:
 np.savez('array_archive.npz', a=arr, b=arr)

In [26]:
arch = np.load('array_archive.npz')

In [30]:
arch['b']
print(arch)

<bound method Mapping.keys of <numpy.lib.npyio.NpzFile object at 0x10c7b3a20>>


In [214]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])

In [215]:
x

array([[1., 2., 3.],
       [4., 5., 6.]])

In [216]:
y = np.array([[6., 23.], [-1, 7], [8, 9]])

In [217]:
y

array([[ 6., 23.],
       [-1.,  7.],
       [ 8.,  9.]])

In [218]:
 x.dot(y) # equivalently np.dot(x, y)

array([[ 28.,  64.],
       [ 67., 181.]])

In [219]:
np.dot(x, np.ones(3))

array([ 6., 15.])

numpy.linalg has a standard set of matrix decompositions and things like inverse and determinant.

In [220]:
from numpy.linalg import inv, qr

In [221]:
X = np.random.randn(5, 4)

In [222]:
mat = X.T.dot(X)
mat

array([[ 1.2952312 , -0.64326745, -1.88624561,  0.3834945 ],
       [-0.64326745,  1.04584129,  1.93829329,  0.2420192 ],
       [-1.88624561,  1.93829329,  7.91224962, -2.94422554],
       [ 0.3834945 ,  0.2420192 , -2.94422554,  5.19795267]])

In [223]:
inv(mat)

array([[ 1.26903431,  0.39166752,  0.20901225,  0.00652574],
       [ 0.39166752,  3.02091417, -0.89931336, -0.67894096],
       [ 0.20901225, -0.89931336,  0.51488838,  0.31809516],
       [ 0.00652574, -0.67894096,  0.31809516,  0.40368933]])

In [224]:
mat.dot(inv(mat))

array([[ 1.00000000e+00,  0.00000000e+00,  3.33066907e-16,
         0.00000000e+00],
       [ 1.66533454e-16,  1.00000000e+00,  2.22044605e-16,
         0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00,
         0.00000000e+00],
       [-1.11022302e-16,  4.44089210e-16,  0.00000000e+00,
         1.00000000e+00]])

In [225]:
q, r = qr(mat)

In [226]:
r

array([[-2.40757293,  2.1055312 ,  8.20058464, -3.2763077 ],
       [ 0.        , -0.94332898, -0.63352447, -2.603571  ],
       [ 0.        ,  0.        , -3.30698046,  4.12322979],
       [ 0.        ,  0.        ,  0.        ,  1.17431652]])

In [227]:
samples = np.random.normal(size=(4, 4))

In [228]:
samples

array([[ 0.25670166, -0.05013215,  1.21362804,  0.74070854],
       [ 0.06120531, -0.26816697,  0.63191713, -0.45058033],
       [-0.15278779,  0.52864555,  0.58982245,  0.24940482],
       [-0.0340902 , -0.91661158,  0.62979465,  1.19086066]])

In [229]:
from random import normalvariate

In [230]:
 N = 1000000

In [231]:
%timeit samples = [normalvariate(0, 1) for _ in range(N)]


828 ms ± 22.4 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [232]:
%timeit np.random.normal(size=N)

34.2 ms ± 932 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


### Random Walks

In [136]:
import random 
import sys
position =0
walk =[position]
steps = 1000
for i in range(steps):
    print(random.randint(0, 1))
    step = 1 if random.randint(0, 1) else -1 
    
    position += step
    walk.append(position)


0
1
0
1
0
1
0
1
1
0
1
0
0
1
0
1
0
1
0
1
0
1
0
1
1
0
1
0
1
0
1
1
1
1
0
1
0
1
0
0
0
1
0
0
0
1
0
1
0
0
1
1
1
1
0
0
0
0
1
0
1
1
0
1
1
0
1
0
1
1
1
0
1
1
0
1
1
1
1
1
1
0
0
1
1
0
0
1
0
1
1
1
1
1
0
1
0
1
1
1
0
0
0
1
0
1
1
1
1
0
0
1
1
0
1
1
0
0
0
0
0
1
0
1
1
1
0
0
0
0
1
1
1
1
0
1
1
0
1
1
0
0
1
0
0
0
1
1
1
1
0
0
0
0
1
0
1
0
0
0
0
0
1
0
0
1
1
1
0
0
0
0
1
0
0
1
0
1
0
0
1
0
0
1
0
0
0
1
0
1
1
0
1
0
0
0
1
0
0
1
1
0
0
1
1
0
1
0
1
1
0
0
1
0
1
1
1
0
1
1
1
0
1
0
0
1
0
0
1
0
1
1
0
0
0
0
1
0
0
1
1
0
0
0
0
1
1
1
1
0
1
1
0
1
0
0
0
1
0
0
0
0
0
0
1
0
0
1
0
0
0
0
1
1
0
0
1
0
0
1
0
0
1
1
1
0
1
0
0
0
1
1
0
1
0
1
0
0
0
1
0
0
0
1
1
1
0
0
1
0
1
1
1
1
1
1
1
1
1
1
1
1
1
0
1
1
0
1
0
0
0
0
0
1
0
1
0
1
0
0
1
1
0
1
0
1
0
0
1
1
0
1
0
0
1
1
1
1
0
1
0
0
0
0
1
0
0
0
1
1
0
0
1
0
0
0
0
0
1
1
1
1
0
1
1
1
0
0
1
0
0
0
0
0
1
0
0
0
1
1
0
0
1
1
0
0
1
1
0
1
0
1
0
0
0
1
1
0
0
1
1
1
0
1
1
1
1
1
1
0
0
1
0
1
1
0
0
0
1
0
0
1
1
1
1
1
1
1
1
0
0
1
0
0
1
1
0
1
1
0
0
0
1
0
1
1
1
1
0
0
0
0
1
1
1
0
0
0
0
0
1
1
1
0
1
0
1
0
1
1
0
1
1
1
1
0
1
0
0
1


In [224]:
walk

[0,
 -1,
 0,
 -1,
 -2,
 -3,
 -2,
 -3,
 -4,
 -3,
 -4,
 -5,
 -4,
 -5,
 -6,
 -5,
 -4,
 -3,
 -2,
 -3,
 -4,
 -3,
 -2,
 -1,
 -2,
 -3,
 -2,
 -1,
 -2,
 -1,
 0,
 -1,
 0,
 1,
 2,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 6,
 7,
 8,
 9,
 10,
 11,
 10,
 11,
 12,
 11,
 10,
 9,
 8,
 7,
 8,
 9,
 8,
 9,
 10,
 11,
 12,
 11,
 12,
 11,
 10,
 11,
 10,
 11,
 10,
 11,
 10,
 11,
 10,
 9,
 8,
 7,
 8,
 7,
 8,
 7,
 6,
 5,
 6,
 5,
 4,
 5,
 6,
 5,
 6,
 7,
 6,
 7,
 6,
 7,
 6,
 7,
 6,
 5,
 6,
 7,
 8,
 9,
 8,
 9,
 10,
 11,
 10,
 9,
 8,
 9,
 8,
 9,
 8,
 9,
 10,
 11,
 10,
 11,
 10,
 11,
 10,
 9,
 8,
 9,
 8,
 9,
 10,
 11,
 12,
 11,
 10,
 9,
 10,
 9,
 8,
 7,
 8,
 7,
 8,
 9,
 8,
 9,
 8,
 9,
 10,
 11,
 10,
 11,
 12,
 11,
 10,
 9,
 8,
 7,
 6,
 5,
 6,
 7,
 8,
 9,
 8,
 7,
 6,
 5,
 4,
 3,
 2,
 1,
 2,
 1,
 2,
 1,
 0,
 1,
 2,
 1,
 0,
 -1,
 -2,
 -1,
 -2,
 -1,
 -2,
 -1,
 -2,
 -3,
 -4,
 -5,
 -4,
 -5,
 -6,
 -5,
 -4,
 -3,
 -2,
 -1,
 -2,
 -3,
 -2,
 -3,
 -4,
 -3,
 -4,
 -3,
 -2,
 -3,
 -4,
 -3,
 -4,
 -5,
 -4,
 -5,
 -4,
 -3,
 -4,
 -5,
 -6,
 -5,
 -4,


In [233]:
nsteps = 1000
draws = np.random.randint(0, 2, size=nsteps)
steps = np.where(draws > 0, 1, -1)
walk = steps.cumsum()

In [234]:
walk.min()

-8

In [235]:
walk.max()

49

In [31]:
#Simulating Many Random Walks at Once

nwalks = 5000
nsteps = 1000
draws = np.random.randint(0, 2, size=(nwalks, nsteps)) # 0 or 1
steps = np.where(draws >0 ,1,-1)
walks = steps.cumsum(1)

In [33]:
walks.shape

(5000, 1000)

In [238]:
walks.min()

-130

In [239]:
walks.max()

114

In [240]:
hits30 = (np.abs(walks) >= 30).any(1)

In [241]:
hits30

array([ True,  True,  True, ...,  True,  True,  True])

In [242]:
hits30.sum() # Number that hit 30 or -30

3352

In [243]:
crossing_times = (np.abs(walks[hits30]) >= 30).argmax(1)

In [244]:
crossing_times.mean()

500.6199284009547

### Array Concatenation and Splitting

In [245]:
x = np.array([1, 2, 3])
x

array([1, 2, 3])

In [246]:
y = np.array([3, 2, 1])
y

array([3, 2, 1])

In [247]:
 np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [248]:
z = [99, 99, 99]
z

[99, 99, 99]

In [249]:
np.concatenate([x, y, z])

array([ 1,  2,  3,  3,  2,  1, 99, 99, 99])

In [250]:
grid = np.array([[1, 2, 3],
                 [4, 5, 6]])
grid


array([[1, 2, 3],
       [4, 5, 6]])

In [251]:
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [252]:
np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [253]:
x = np.array([1, 2, 3])
x

array([1, 2, 3])

In [254]:
 grid = np.array([[9, 8, 7],
                [6, 5, 4]])
grid

array([[9, 8, 7],
       [6, 5, 4]])

In [255]:
# vertically stack the arrays
np.vstack([x, grid])


array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [256]:
 #horizontally stack the arrays 
y = np.array([[99],
            [99]])
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

In [257]:
x = [1, 2, 3, 99, 99, 3, 2, 1,2,3,4]

In [258]:
# for split we can pass a list of indices giving the split points:
x1, x2, x3 = np.split(x, [3, 5])

In [259]:
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1 2 3 4]


In [260]:
 grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [261]:
upper, lower = np.vsplit(grid, [2])

In [262]:
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [263]:
left, right = np.hsplit(grid, [2])

In [264]:
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


#### Broadcasting


Broadcasting is simply a set of rules for applying binary ufuncs (addition, subtraction, multiplication, etc.) on arrays of different sizes.

In [265]:
import numpy as np
a = np.array([0, 1, 2])
b = np.array([5, 5, 5])
a+b

array([5, 6, 7])

In [266]:
a+5

array([5, 6, 7])

In [267]:
M = np.ones((3, 3))

In [268]:
M


array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [269]:
M+a

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [270]:
a = np.arange(3)
a


array([0, 1, 2])

In [271]:
b = np.arange(3)[:, np.newaxis]
b

array([[0],
       [1],
       [2]])

In [272]:
a+b

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

### Rules of Broadcasting

Rule 1: If the two arrays differ in their number of dimensions, the shape of the one with fewer dimensions is padded with ones on its leading (left) side.

Rule 2: If the shape of the two arrays does not match in any dimension, the array with shape equal to 1 in that dimension is stretched to match the other shape.

Rule 3: If in any dimension the sizes disagree and neither is equal to 1, an error is raised.

In [274]:
# adding a two-dimensional array to a one-dimensional array:
M = np.ones((2, 3))
a = np.arange(3,)

In [275]:
print(M)
print(a)

[[1. 1. 1.]
 [1. 1. 1.]]
[0 1 2]


In [276]:
M.shape

(2, 3)

In [277]:
a.shape

(3,)

by rule 1 that the array a has fewer dimensions, so we pad it on the left with ones:

M.shape -> (2, 3)

a.shape -> (1, 3)

rule 2, we now see that the first dimension disagrees, so we stretch this dimension to match:

M.shape -> (2, 3)

a.shape -> (2, 3)



In [278]:
M + a

array([[1., 2., 3.],
       [1., 2., 3.]])

In [279]:
## example where both arrays needed broad cast 
a = np.arange(3).reshape((3, 1))
b = np.arange(3)

In [280]:
a.shape

(3, 1)

In [281]:
b.shape

(3,)


Rule 1 says we must pad the shape of b with ones:

a.shape -> (3, 1)

b.shape -> (1, 3)

And rule 2 tells us that we upgrade each of these ones to match the corresponding size of the other array:

 a.shape -> (3, 3)
 
 b.shape -> (3, 3)

In [282]:
a+b

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [283]:
## example in which the two arrays are not compatible:
M = np.ones((3, 2))

In [284]:
 a = np.arange(3)

In [285]:
M


array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [286]:
M.shape

(3, 2)

In [287]:
 a.shape 

(3,)

In [288]:
a

array([0, 1, 2])

rule 1 tells us that we must pad the shape of a with ones:

M.shape -> (3, 2)

a.shape -> (1, 3)

rule 2, the first dimension of a is stretched to match that of M:

M.shape -> (3, 2)

a.shape -> (3, 3)

rule 3—the final shapes do not match, so these two arrays are incompati‐ ble, as we can observe by attempting this operation:

In [293]:
M+a.T

ValueError: operands could not be broadcast together with shapes (3,2) (3,) 

potential confusion here: you could imagine making a and M compatible by, say, padding a’s shape with ones on the right rather than the left. But this is not how the broadcasting rules work! That sort of flexibility might be useful in some cases, but it would lead to potential areas of ambiguity.

In [290]:
a[:, np.newaxis].shape

(3, 1)

In [291]:
 M + a[:, np.newaxis]

array([[1., 1.],
       [2., 2.],
       [3., 3.]])

these broadcasting rules apply to any binary ufunc.

logaddexp(a, b) function, which computes log(exp(a) + exp(b)) with more precision than the naive approach:


In [292]:
np.logaddexp(M, a[:, np.newaxis])

array([[1.31326169, 1.31326169],
       [1.69314718, 1.69314718],
       [2.31326169, 2.31326169]])